# Site
name: "Panquet"
title: "Yeet1"
description: "Documenting weird and wonderful creatures! \n To be updated soon.."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /panquet.github.io
google_analytics: ''
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: site@panquet.com.au

# Authors
authors:
  Seb:
    name: Seb
    display_name: Baz
    avatar: 'assets/images/avatar-seb.png'
    email: site@panquet.com.au
    web: https://panquet.com.au
    twitter: https://x.com/elonmusk
    description: "Very cool."
  Tristan:
    name: Tristan
    display_name: T    
    avatar: 'assets/images/avatar-T.png'
    email: site@panquet.com.au
    web: https://panquet.com.au
    twitter: https://x.com/elonmusk
    description: "Not that cool."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
